In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9621, 3787, 1109, 2096],
 [9621, 3787, 1109, 5652],
 [9621, 3832, 1109, 8565],
 [2932, 7625, 9484, 4546, 4170],
 [2932, 7625, 9484, 4546, 462],
 [2146, 9621, 6799, 1109, 1519],
 [4696, 9312, 7498, 4546]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9621 3787 1109 2096]
 [   0    0    0    0 9621 3787 1109 5652]
 [   0    0    0    0 9621 3832 1109 8565]
 [   0    0    0 2932 7625 9484 4546 4170]
 [   0    0    0 2932 7625 9484 4546  462]
 [   0    0    0 2146 9621 6799 1109 1519]
 [   0    0    0    0 4696 9312 7498 4546]]


In [11]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step


array([[[-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [ 0.03249623, -0.01120784,  0.01927961,  0.01872952,
          0.02331004,  0.00138266, -0.01405613, -0.01069528,
          0.01053187,  0.01359829],
        [ 0.03555712,  0.00544574, -0.00446017, -0.04169117,
         -0.02367051,  0.02234435, -0.03107947,  0.02483252,
         -0.02869424, -0.0138258 ],
        [ 0.02086985, -0.00401703, -0.03598894, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9621, 3787, 1109, 2096], dtype=int32)

In [19]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [-0.04765543, -0.04652924,  0.04071936, -0.0027897 ,
         -0.02523209, -0.01776201,  0.00484854, -0.03871925,
          0.04563055, -0.03549914],
        [ 0.03249623, -0.01120784,  0.01927961,  0.01872952,
          0.02331004,  0.00138266, -0.01405613, -0.01069528,
          0.01053187,  0.01359829],
        [ 0.03555712,  0.00544574, -0.00446017, -0.04169117,
         -0.02367051,  0.02234435, -0.03107947,  0.02483252,
         -0.02869424, -0.0138258 ],
        [ 0.02086985, -0.00401703, -0.03598894, -0.0